export const invitationConceptCodes = [
  "love-poem",
  "garden-night",
  "moonlight",
  "golden-vows",
  "white-story",
  "cinema-night",
  "rose-garden",
  "cathedral-light",
  "desert-sunset",
  "velvet-night",
  "coastal-breeze",
  "modern-monogram",
] as const;

export type InvitationConcept = (typeof invitationConceptCodes)[number];

const invitationConceptByName: Record<string, InvitationConcept> = {
  "قصيدة حب": "love-poem",
  "أناقة التحرير": "love-poem",
  "Love Poem": "love-poem",
  "Élan Editorial": "love-poem",
  "ليلة في الحديقة": "garden-night",
  "حُلم الحديقة": "garden-night",
  "Garden Night": "garden-night",
  "Garden Reverie": "garden-night",
  "نور القمر": "moonlight",
  "قمر زجاجي": "moonlight",
  Moonlight: "moonlight",
  "Glass Moon": "moonlight",
  "عهود ذهبية": "golden-vows",
  "الوعد المُذهّب": "golden-vows",
  "Golden Vows": "golden-vows",
  "Gilded Promise": "golden-vows",
  "حكاية بيضاء": "white-story",
  "سُكون": "white-story",
  "White Story": "white-story",
  Still: "white-story",
  "ليلة سينمائية": "cinema-night",
  "وهج الغروب": "cinema-night",
  "Cinema Night": "cinema-night",
  "After Dark": "cinema-night",
  "Afterglow Première": "cinema-night",
  "حديقة الورد": "rose-garden",
  "وردة حالمة": "rose-garden",
  "Rose Garden": "rose-garden",
  "Blush Botanica": "rose-garden",
  "نور الكاتدرائية": "cathedral-light",
  "الميثاق الملكي": "cathedral-light",
  "Cathedral Light": "cathedral-light",
  "The Royal Chapel": "cathedral-light",
  "غروب الصحراء": "desert-sunset",
  "صفحات الغروب": "desert-sunset",
  "Desert Sunset": "desert-sunset",
  "Sunlit Pages": "desert-sunset",
  "ليلة مخملية": "velvet-night",
  "العرض المخملي": "velvet-night",
  "Velvet Night": "velvet-night",
  "Velvet Première": "velvet-night",
  "نسيم الساحل": "coastal-breeze",
  "عهود الساحل": "coastal-breeze",
  "Coastal Breeze": "coastal-breeze",
  "Barefoot Vows": "coastal-breeze",
  "حروفنا": "modern-monogram",
  "حروف النور": "modern-monogram",
  "Modern Monogram": "modern-monogram",
  "Noor Monogram": "modern-monogram",
};

export function resolveInvitationConcept(templateName: string): InvitationConcept {
  return invitationConceptByName[templateName] ?? "love-poem";
}
